name: 'Dependency Review'
on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:  # Add this to allow manual triggering

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || '' }}
          head_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || '' }}
